### ISSUE TITLE
npm issue

### ISSUE THREAD

**Issue by Hoangtho11188** [opentrace-community/opentrace-android#16] opened 2020-04-16 08:49 UTC
I have a issue at below step : 
opentrace-cloud-functions>npm --prefix functions install
npm ERR! Can't install : Missing package version

Could you pls help me on this?

**Comment by achrinza** [comment] 2020-04-16 09:19
This issue is probably more suited in https://github.com/opentrace-community/opentrace-cloud-functions

Try the following:
• Ensure the latest Node.js LTS version is used
• Update NPM with `npm install -g npm`

**Comment by Hoangtho11188** [comment] 2020-04-16 09:29
> This issue is probably more suited in https://github.com/opentrace-community/opentrace-cloud-functions
> 
> Try the following:
> • Ensure the latest Node.js LTS version is used
> • Update NPM with `npm install -g npm`

Yes, updated and this issue still appeared :(
I'm stuck at this step .

**Comment by esQmo** [comment] 2020-04-16 16:44
Mee too, and this guide is poorly writen! You need to show step by step guide!

**Comment by achrinza** [comment] 2020-04-17 02:09
In the spirit of nurturing a healthy FOSS community, let's try to keep the conversation civil.

I'm not too sure why the docs suggest using `--prefix`, but could you try the following:

1. `cd functions`

    This would put you in the same directory as `package.json`, thereby removing the need to use `--prefix`

2. `npm ci`

    I recommend this command over `npm install` as it makes use of package locks, thereby making the installation reproducible.

Further reading:

- https://docs.npmjs.com/using-npm/config.html#prefix
- https://docs.npmjs.com/cli-commands/ci.html

**Comment by achrinza** [comment] 2020-04-17 02:10
Duplicate of https://github.com/opentrace-community/opentrace-cloud-functions/issues/14

**Comment by achrinza** [comment] 2020-04-17 02:20
I'm still unable to replicate the issue from my end. Could you run the following command:

- `node -e "console.log(process.platform, process.arch, process.versions.node)"`

... and then post it here?

Here's mine:

```sh
win32 x64 12.16.1
```

---

Also, could you try adding this key-value into `package.json`, and then retry the install process?

```json
"version": "0.0.1"
```

**Comment by Hoangtho11188** [comment] 2020-04-17 03:41
> I'm still unable to replicate the issue from my end. Could you run the following command:
> 
> * `node -e "console.log(process.platform, process.arch, process.versions.node)"`
> 
> ... and then post it here?
> 
> Here's mine:
> 
> ```shell
> win32 x64 12.16.1
> ```
> 
> Also, could you try adding this key-value into `package.json`, and then retry the install process?
> 
> ```json
> "version": "0.0.1"
> ```

Thanks for your support, it's OK now, deploy the functions to firebase succeed.
Now I'm facing with this issue when run app : 
**NOT-IDLE Failed to retrieve HandShakePin NOT_FOUND**
Could you pls give some advise for this?

**Comment by achrinza** [comment] 2020-04-17 03:55
@Hoangtho11188 Issue #9 addresses this concern. Could you take a look at the thread there?

**Closed as completed** 2020-04-17 03:54 UTC

**Comment by Hoangtho11188** [comment] 2020-04-17 03:55
> @Hoangtho11188 Issue #9 addresses this concern. Could you take a look at the thread there?

it's ok now, thanks so much @achrinza :)

**Comment by Hoangtho11188** [comment] 2020-04-17 09:14
@achrinza One more question, how do we test this app?
Ex : with 2 devices (installed this app)
- how can we know that : they were connected or not?
- And about functions "Upload data" : how can we get correct PIN in this case? and how to check on Firebase storage?
Thank in advance for your help!

**Comment by achrinza** [comment] 2020-04-18 14:12
Hi @Hoangtho11188, apologies for the delayed reply. Unfortunately my knowledge of the OpenTrace project is rather limited, so I can't really help out in answering those queries.

There's a number of issues mentioning OTP throughout the different repos, could you check those out?

**Comment by achrinza** [comment] 2020-04-18 15:10
To quote @rinekri (taken from https://github.com/opentrace-community/opentrace-android/issues/10#issuecomment-613891782):

>you can double tap on logo at first tab to open a debug screen. If everything is okey you will see cards with an exchanged information.

Not too sure if it works on the Android app, but I thought it's worth a mention.

**Comment by rinekri** [comment] 2020-04-18 16:47
> To quote @rinekri (taken from [#10 (comment)](https://github.com/opentrace-community/opentrace-android/issues/10#issuecomment-613891782)):
> 
> > you can double tap on logo at first tab to open a debug screen. If everything is okey you will see cards with an exchanged information.
> 
> Not too sure if it works on the Android app, but I thought it's worth a mention.

I 100% sure that it works :)

**Comment by Hoangtho11188** [comment] 2020-04-19 03:17
> > To quote @rinekri (taken from [#10 (comment)](https://github.com/opentrace-community/opentrace-android/issues/10#issuecomment-613891782)):
> > > you can double tap on logo at first tab to open a debug screen. If everything is okey you will see cards with an exchanged information.
> > 
> > 
> > Not too sure if it works on the Android app, but I thought it's worth a mention.
> 
> I 100% sure that it works :)

My app crash when did this step.On debugging. :)

**Comment by rinekri** [comment] 2020-04-19 04:37
> > > To quote @rinekri (taken from [#10 (comment)](https://github.com/opentrace-community/opentrace-android/issues/10#issuecomment-613891782)):
> 
> > > > you can double tap on logo at first tab to open a debug screen. If everything is okey you will see cards with an exchanged information.
> 
> > > 
> 
> > > 
> 
> > > Not too sure if it works on the Android app, but I thought it's worth a mention.
> 
> > 
> 
> > I 100% sure that it works :)
> 
> 
> 
> My app crash when did this step.On debugging. :)

Wow, check logs from logcat, maybe something is not initialized correctly or your device doesn’t support something what app uses in debug mode.

**Comment by Hoangtho11188** [comment] 2020-04-20 07:08
![device-2020-04-20-140523](https://user-images.githubusercontent.com/45715294/79723482-0c760d00-8310-11ea-9e6c-e370fe56c6a0.png)
@rinekri Empty screen when double tap on logo. I have 2 devices, seem as they weren't connected.Do you have any advice or suggestion?
